### ISSUE TITLE
(Question/Suggestion) Why is run registry necessary?

### ISSUE THREAD

**Issue by hulkish** [resdir/resdir#1]
First, I wanna say that I really think this is a great idea. I think this is potentially a great solution to better organized tooling. 

However, I have a few questions/concerns:
- Why is it necessary to introduce a new package management system? 
- This adds overhead in terms of maintenance. 
- Why can't npm registry handle this?
- Consider bower as an example of why this may not be an easy path. Juggling bower + npm dependencies was a nightmare. 

Thanks!

**Comment by mvila** [comment]
Thanks, @hulkish, here is my answer: https://github.com/runtools/run/issues/6#issuecomment-373966453
